// Fetches the HTML page.
GET {{baseUrl}}
Accept: text/html

###

// Fetches a resource embedded in the data file.
GET {{baseUrl}}?file=js/main.js
Accept: application/javascript

###

// Fetches the directory listing.
GET {{baseUrl}}?listing
Accept: application/json
