### Fetches the HTML page.
GET {{apiUrl}}/
Accept: text/html

### Fetches a resource embedded in the data file.
GET {{apiUrl}}/?file=js/main.js
Accept: text/javascript

### Fetches the PHP information.
GET {{apiUrl}}/?phpinfo
Accept: application/json

### Fetches the directory listing.
GET {{apiUrl}}/?listing
Accept: application/json
