// Fetches the HTML page.
GET {{apiUrl}}
Accept: text/html

###

// Fetches a resource embedded in the data file.
GET {{apiUrl}}?file=js/main.js
Accept: application/javascript

###

// Fetches the directory listing.
GET {{apiUrl}}?listing
Accept: application/json
