// Returns the HTML page.
GET {{baseUrl}}
Accept: text/html

###

// Returns a script.
GET {{baseUrl}}?file=js/main.js
Accept: application/javascript

###

// Returns a stylesheet.
GET {{baseUrl}}?file=css/main.css
Accept: text/css

###

// Returns the directory listing.
GET {{baseUrl}}?index
Accept: application/json

###
